name: Laravel

on:
  push:
    branches: ["l3software"]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: "l3software.com.br"
          username: ${{ secrets.FTP_USERNAME_L3 }}
          password: ${{ secrets.FTP_PASSWORD_L3 }}
          port: 22
          server-dir: "/cajueiro.l3sistemas.com.br/api/"
